blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('blog/comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),  # Incluye la aplicación de usuarios
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True) 

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.post}'

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.http import HttpResponseForbidden
from usuarios.models import DatosExtra

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post).select_related('author__datosextra')
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect('post_detail', pk=post.pk)
        else:
            messages.warning(request, "You need to be logged in to add a comment.")
            return redirect('login')
    else:
        form = CommentForm()
    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'form': form})

@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES) 
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return HttpResponseForbidden("You are not allowed to delete this post.")
    
    post.delete()
    return redirect('post_list')

@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author != request.user:
        return HttpResponseForbidden("You are not allowed to delete this comment.")
    post_id = comment.post.id
    comment.delete()
    return redirect('post_detail', pk=post_id)

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Detalle - Guitar Heaven{% endblock %}

{% block navbar %}
{{ block.super }}
{% endblock navbar %}

{% block main %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article class="card mb-4">
                <header class="card-header">
                    <!-- Avatar del autor del post -->
                    {% if post.author.datosextra.avatar %}
                        <img src="{{ post.author.datosextra.avatar.url }}" class="avatar" alt="{{ post.author.username }}'s avatar">
                    {% else %}
                        <img src="{% static 'images/default_avatar.png' %}" class="avatar" alt="Default avatar">
                    {% endif %}
                    <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
                    <div class="text-muted fst-italic mb-2">Posteado por {{ post.author }} || {{ post.created_at }} ||</div>
                </header>
                <section class="card-body">
                    <p class="fs-5 mb-4">{{ post.content }}</p>
                    {% if post.image %}
                        <img src="{{ post.image.url }}" style="max-width: 100%; height: auto; width: 300px;" alt="Post image">
                    {% endif %}
                    {% if post.author == request.user %}
                    <form action="{% url 'delete_post' post.id %}" method="POST" class="mt-3">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Eliminar Post</button>
                    </form>
                    {% endif %}
                </section>
            </article>
            <!-- Comments section-->
            <section class="mb-5">
                <div class="card bg-dark">
                    <div class="card-body">
                        <!-- Comment form-->
                        {% if request.user.is_authenticated %}
                            <form method="post" class="mb-4">
                                {% csrf_token %}
                                <textarea class="form-control" name="content" rows="3"></textarea>
                                <button type="submit" class="btn btn-primary mt-2">Agregar Comentario</button>
                            </form>
                        {% else %}
                            <div class="alert alert-warning" role="alert">
                                Necesitas loguearte para comentar.
                            </div>
                        {% endif %}
                        <!-- Comments list-->
                        {% for comment in comments %}
                            <div class="d-flex mb-4">
                                <div class="flex-shrink-0">
                                    <!-- Avatar del autor del comentario -->
                                    {% if comment.author.datosextra.avatar %}
                                        <img src="{{ comment.author.datosextra.avatar.url }}" alt="Avatar" class="avatar">
                                    {% else %}
                                        <img src="{% static 'images/default_avatar.png' %}" class="avatar" alt="Default avatar">
                                    {% endif %}
                                </div>
                                <div class="ms-3">
                                    <div class="fw-bold">{{ comment.author }}</div>
                                    {{ comment.content }}
                                </div>
                                {% if comment.author == request.user %}
                                <div class="ms-3">
                                    <form action="{% url 'delete_comment' comment.id %}" method="POST" style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-sm">Eliminar Comentario</button>
                                    </form>
                                </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
        </div>
        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Categories widget-->
            <div class="card mb-4 bg-dark">
                <div class="card-header">Categorias</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a class="text-white" href="{% url 'post_list' %}">Blog</a></li>
                                <li><a class="text-white" href="{% url 'post_new' %}">Nuevo post</a></li>
                                <li><a class="text-white" href="{% url 'crear_guitar' %}">Vota tu guitar</a></li>
                                <li><a class="text-white" href="{% url 'guitars' %}">Listado</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

blog/templates/blog/post_edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edit - Guitar Heaven{% endblock %}

{% block navbar %}
{{ block.super }}
{% endblock navbar %}

{% block main %}
<div class="container mt-5">
    <h1 class="fw-bolder mb-4">Create a New Post</h1>
    <div class="card bg-dark">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <label for="id_title" class="form-label">Title</label>
                    {{ form.title }}
                </div>
                <div class="form-group mb-3">
                    <label for="id_content" class="form-label">Content</label>
                    {{ form.content }}
                </div>
                <div class="form-group mb-3">
                    <label for="id_image" class="form-label">Image</label>
                    {{ form.image }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock main %}

blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Lista - Guitar Heaven{% endblock %}

{% block navbar %}
{{ block.super }}
{% endblock navbar %}

{% block main %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post list-->
            <h1 class="fw-bolder mb-4">Blog Posts</h1>
            {% if not request.user.is_authenticated %}
                <p>Para postear primero <a href="{% url 'login' %}">logueate</a>.</p>
            {% endif %}
            {% for post in posts %}
            <div class="card mb-4 bg-dark">
                <div class="card-body">
                    <!-- Avatar del autor del post -->
                    {% if post.author.datosextra.avatar %}
                        <img src="{{ post.author.datosextra.avatar.url }}" alt="Avatar" class="avatar">
                    {% else %}
                        <img src="{% static 'images/default_avatar.png' %}" class="avatar" alt="Default avatar">
                    {% endif %}
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text">{{ post.content|truncatewords:30 }}</p>
                    <a href="{% url 'post_detail' post.pk %}" class="btn btn-primary">Leer Mas →</a>
                </div>
            </div>
            {% empty %}
            <p>No hay posts disponibles.</p>
            {% endfor %}
        </div>
        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Categories widget-->
            <div class="card mb-4 bg-dark">
                <div class="card-header">Categorias</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a class="text-white" href="{% url 'post_list' %}">Blog</a></li>
                                <li><a class="text-white" href="{% url 'post_new' %}">Nuevo post</a></li>
                                <li><a class="text-white" href="{% url 'crear_guitar' %}">Vota tu guitar</a></li>
                                <li><a class="text-white" href="{% url 'guitars' %}">Listado</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}