blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('blog/comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),  # Incluye la aplicación de usuarios
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('registro/', views.registro, name='register'),
    path('perfil/ver/', views.ver_perfil, name='ver_perfil'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/password/', views.CambiarPassword.as_view(), name='cambiar_pass'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class DatosExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', blank=True, null=True)

    def __str__(self):
        return self.user.username

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from usuarios.models import DatosExtra

class NuestroFormularioDeCreacion(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {key: '' for key in fields}

class EditarPerfil(UserChangeForm):
    password = None
    email = forms.EmailField()
    first_name = forms.CharField(label='Nombre')
    last_name = forms.CharField(label='Apellido')
    avatar = forms.ImageField(required=False)
    
    class Meta:
        model = DatosExtra  # Cambiado a DatosExtra para incluir el campo avatar
        fields = ['email', 'first_name', 'last_name', 'avatar']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['avatar'].widget.attrs.update({'class': 'form-control'})

class VerPerfilForm(forms.ModelForm):
    username = forms.CharField(label='Nombre de usuario', required=False, widget=forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}))
    email = forms.EmailField(label='Email', required=False, widget=forms.EmailInput(attrs={'readonly': True, 'class': 'form-control'}))
    first_name = forms.CharField(label='Nombre', required=False, widget=forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}))
    last_name = forms.CharField(label='Apellido', required=False, widget=forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}))
    avatar = forms.ImageField(label='Avatar', required=False, widget=forms.ClearableFileInput(attrs={'readonly': True, 'class': 'form-control'}))

    class Meta:
        model = DatosExtra
        fields = ['username', 'email', 'first_name', 'last_name', 'avatar']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        user = self.instance.user
        self.fields['username'].initial = user.username
        self.fields['email'].initial = user.email
        self.fields['first_name'].initial = user.first_name
        self.fields['last_name'].initial = user.last_name

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login as django_login, logout
from usuarios.forms import NuestroFormularioDeCreacion, EditarPerfil, VerPerfilForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from usuarios.models import DatosExtra

def login(request):
    formulario = AuthenticationForm()
    
    if request.method == 'POST':
        formulario = AuthenticationForm(data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data.get('username')
            contrasenia = formulario.cleaned_data.get('password')
        
            user = authenticate(request, username=usuario, password=contrasenia)

            if user is not None:
                django_login(request, user)
                DatosExtra.objects.get_or_create(user=user)
                return redirect('home')
    
    return render(request, 'usuarios/login.html', {'formulario': formulario})

def registro(request):
    formulario = NuestroFormularioDeCreacion()
    
    if request.method == "POST":
        formulario = NuestroFormularioDeCreacion(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('login')
    
    return render(request, 'usuarios/registro.html', {'formulario': formulario})

@login_required
def ver_perfil(request):
    datos_extra, created = DatosExtra.objects.get_or_create(user=request.user)
    form = VerPerfilForm(instance=datos_extra)
    return render(request, 'usuarios/ver_perfil.html', {'form': form})

@login_required
def editar_perfil(request):
    datos_extra, created = DatosExtra.objects.get_or_create(user=request.user)
    if request.method == "POST":
        formulario = EditarPerfil(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            formulario.save()
            avatar = formulario.cleaned_data.get('avatar')
            if avatar:
                datos_extra.avatar = avatar
            datos_extra.save()
            return redirect('ver_perfil')   
    else:
        formulario = EditarPerfil(instance=request.user)

    return render(request, 'usuarios/editar_perfil.html', {'formulario': formulario})

class CambiarPassword(PasswordChangeView):
    template_name = 'usuarios/cambiar_pass.html'
    success_url = reverse_lazy('editar_perfil')

def custom_logout(request):
    logout(request)
    return render(request, 'usuarios/logout_confirmation.html')

usuarios/templates/usuarios/cambiar_pass.html
{% extends "base.html" %}
{% load static %}

{% block title %}Cambiar Contraseña - Guitar Heaven{% endblock %}

{% block navbar %}
{{ block.super }}
{% endblock navbar %}

{% block main %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <div class="card bg-dark text-white">
                <div class="card-header text-center">
                    <h3>Cambiar Contraseña</h3>
                </div>
                <div class="card-body">
                    <form action="{% url 'cambiar_pass' %}" method="POST">
                        {% csrf_token %}
                        
                        <div class="mb-3">
                            {{ form.old_password.label_tag }} 
                            {{ form.old_password }}
                            {% if form.old_password.errors %}
                                <div class="invalid-feedback d-block">
                                    {% for error in form.old_password.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="mb-3">
                            {{ form.new_password1.label_tag }} 
                            {{ form.new_password1 }}
                            {% if form.new_password1.errors %}
                                <div class="invalid-feedback d-block">
                                    {% for error in form.new_password1.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="mb-3">
                            {{ form.new_password2.label_tag }} 
                            {{ form.new_password2 }}
                            {% if form.new_password2.errors %}
                                <div class="invalid-feedback d-block">
                                    {% for error in form.new_password2.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Cambiar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

usuarios/templates/usuarios/editar_perfil.html
{% extends "base.html" %}
{% load static %}

{% block title %}Registro - Guitar Heaven{% endblock %}

{% block navbar %}
{{ block.super }}
{% endblock navbar %}

{% block main %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card bg-dark">
                <div class="card-header text-center">Edit Profile</div>
                <div class="card-body">
                    <form action="{% url 'editar_perfil' %}" method="POST" enctype='multipart/form-data'>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_email" class="form-label">Email:</label>
                            <input type="email" id="id_email" name="email" class="form-control" value="{{ formulario.email.value }}">
                        </div>
                        <div class="form-group">
                            <label for="id_first_name" class="form-label">First Name:</label>
                            <input type="text" id="id_first_name" name="first_name" class="form-control" value="{{ formulario.first_name.value }}">
                        </div>
                        <div class="form-group">
                            <label for="id_last_name" class="form-label">Last Name:</label>
                            <input type="text" id="id_last_name" name="last_name" class="form-control" value="{{ formulario.last_name.value }}">
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="id_avatar" class="form-label">Avatar:</label>
                                {% if request.user.datosextra.avatar %}
                                <img src="{{ request.user.datosextra.avatar.url }}" alt="Avatar actual" width="100">
                                {% endif %}
                                <input type="file" id="id_avatar" name="avatar" class="form-control">
                            </div>
                        </div>
                        <input type="submit" value="Editar" class="btn btn-primary mt-3">
                    </form>
                    <a href="{% url 'cambiar_pass' %}" class="btn btn-secondary mt-3">Cambiar contraseña</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

usuarios/templates/usuarios/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}Registro - Guitar Heaven{% endblock %}

{% block navbar %}
{{ block.super }}
{% endblock navbar %}

{% block main %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card bg-dark">
                <div class="card-header text-center">Login</div>
                <div class="card-body">
                    <form action={% url "login" %} method="POST">
                        {% csrf_token %}
                    
                        {{formulario}}
                    
                        <input type="submit" value="Iniciar Sesion">
                    
                    </form>
                    <div class="mt-3 text-center">
                        <p>Don't have an account? <a href="{% url 'register' %}" class="text-primary">Register</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

usuarios/templates/usuarios/logout_confirmation.html
{% extends "base.html" %}
{% load static %}

{% block title %}Logout - Guitar Heaven{% endblock %}

{% block navbar %}
{{ block.super }}
{% endblock navbar %}

{% block main %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card bg-dark">
                <div class="card-header text-center">Are you sure you want to logout?</div>
                <div class="card-body text-center">
                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <div class="d-grid">
                            <a href="{% url 'home' %}" class="btn btn-primary mb-2">Logout</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

usuarios/templates/usuarios/registro.html
{% extends "base.html" %}
{% load static %}

{% block title %}Registro - Guitar Heaven{% endblock %}

{% block navbar %}
{{ block.super }}
{% endblock navbar %}

{% block main %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card bg-dark">
                    <div class="card-header text-center">Register</div>
                    <div class="card-body">
                        <form action={% url "register" %} method="POST">
                            {% csrf_token %}
                        
                            {{formulario}}
                        
                            <input type="submit" value="Registrarse">
                        
                        </form>
                        <div class="mt-3 text-center">
                            <p>Already have an account? <a href="{% url 'login' %}" class="text-primary">Login</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

usuarios/templates/usuarios/ver_perfil.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="User Profile - Guitar Heaven" />
    <meta name="author" content="Guitar Heaven" />
    <title>User Profile - Guitar Heaven</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <style>
        body, .navbar, .card, .card-header, .card-body, footer {
            background-color: #343a40;
            color: white;
        }
        .nav-link, .navbar-brand {
            color: white !important;
        }
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }
        .form-control {
            background-color: #495057;
            color: white;
            border: 1px solid #6c757d;
        }
        .form-control:focus {
            background-color: #495057;
            color: white;
            border-color: #007bff;
        }
        .avatar {
            float: left;
            margin-right: 20px;
            max-width: 200px;
            margin-bottom: 10px;
        }
        .list-group-item {
            background-color: #495057; /* Color oscuro similar al fondo general */
            border-color: #343a40; /* Color del borde */
        }
    </style>
</head>
<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About Us</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page content-->
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card bg-dark">
                    <div class="card-header text-center">User Profile</div>
                    <div class="card-body">
                        {% if user.datosextra.avatar %}
                        <img src="{{ user.datosextra.avatar.url }}" alt="Avatar" class="avatar">
                        {% else %}
                        <img src="{% static 'images/default_avatar.png' %}" class="avatar" alt="Default avatar">
                        {% endif %}
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <strong>Username:</strong> {{ user.username }}
                            </li>
                            <li class="list-group-item">
                                <strong>Email:</strong> {{ user.email }}
                            </li>
                            <li class="list-group-item">
                                <strong>First Name:</strong> {{ user.first_name }}
                            </li>
                            <li class="list-group-item">
                                <strong>Last Name:</strong> {{ user.last_name }}
                            </li>
                            <li class="list-group-item">
                                <strong>Joined:</strong> {{ user.date_joined|date:"F d, Y" }}
                            </li>
                        </ul>
                        <a href="{% url 'editar_perfil' %}" class="btn btn-primary mt-3">Editar perfil</a>
                        <a href="{% url 'cambiar_pass' %}" class="btn btn-secondary mt-3">Cambiar contraseña</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Guitar Heaven 2024</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>